language: generic 
sudo: required
services:
  - docker
before_install:
  - docker build -t docker_react -f Dockerfile.dev .
script:
  - docker run -e CI=true docker_react npm run test
Deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "Docker_React"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-866550553578"
  bucket_path:  "Docker_React"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY